// src/config/niches.js
// Every niche the app supports. Chosen during onboarding, this drives
// default categories, terminology and niche-specific product fields.
import {
  ShoppingBasket,
  Footprints,
  Pill,
  UtensilsCrossed,
  Scissors,
  Store,
} from 'lucide-react';

export const NICHES = [
  {
    value: 'supermarket',
    label: 'Supermarket / Minimart',
    tagline: 'Groceries, drinks & everyday goods',
    icon: ShoppingBasket,
    itemNoun: 'Product',
    itemNounPlural: 'Products',
    trackStock: true,
    hasExpiry: false,
    hasBarcode: true,
    categories: [
      'Beverages',
      'Snacks & Confectionery',
      'Food Cupboard & Dry Foods',
      'Fresh & Frozen',
      'Toiletries & Personal Care',
      'Household & Cleaning',
      'Baby & Kids',
    ],
  },
  {
    value: 'bags_shoes',
    label: 'Bags & Shoes / Boutique',
    tagline: 'Fashion, footwear & accessories',
    icon: Footprints,
    itemNoun: 'Product',
    itemNounPlural: 'Products',
    trackStock: true,
    hasExpiry: false,
    hasBarcode: true,
    categories: [
      'Ladies Handbags',
      "Men's Shoes",
      'Ladies Shoes',
      'School Bags & Backpacks',
      'Travel Bags & Boxes',
      'Slippers & Sandals',
      'Kids Shoes',
      'Accessories (Belts, Wallets, Caps)',
    ],
  },
  {
    value: 'pharmacy',
    label: 'Pharmacy',
    tagline: 'Medicines & health products with expiry tracking',
    icon: Pill,
    itemNoun: 'Product',
    itemNounPlural: 'Products',
    trackStock: true,
    hasExpiry: true,
    hasBarcode: true,
    categories: [
      'Prescription Drugs',
      'Over-the-Counter',
      'Vitamins & Supplements',
      'First Aid',
      'Personal Care',
      'Baby & Mother',
      'Medical Devices',
    ],
  },
  {
    value: 'restaurant',
    label: 'Restaurant / Bar',
    tagline: 'Meals, drinks & quick service',
    icon: UtensilsCrossed,
    itemNoun: 'Menu Item',
    itemNounPlural: 'Menu Items',
    trackStock: false,
    hasExpiry: false,
    hasBarcode: false,
    categories: [
      'Main Dishes',
      'Soups & Swallow',
      'Grills & Proteins',
      'Rice & Pasta',
      'Soft Drinks',
      'Beer & Spirits',
      'Desserts & Small Chops',
    ],
  },
  {
    value: 'salon',
    label: 'Salon / Services',
    tagline: 'Services, bookings & retail add-ons',
    icon: Scissors,
    itemNoun: 'Service',
    itemNounPlural: 'Services',
    trackStock: false,
    hasExpiry: false,
    hasBarcode: false,
    categories: [
      'Haircuts & Styling',
      'Braids & Weaves',
      'Nails & Pedicure',
      'Makeup & Gele',
      'Spa & Massage',
      'Retail Products',
    ],
  },
  {
    value: 'other',
    label: 'Other Business',
    tagline: 'General merchandise or anything else',
    icon: Store,
    itemNoun: 'Product',
    itemNounPlural: 'Products',
    trackStock: true,
    hasExpiry: false,
    hasBarcode: true,
    categories: ['General Merchandise', 'Accessories', 'Services'],
  },
];

export function getNiche(value) {
  return NICHES.find((n) => n.value === value) || NICHES[NICHES.length - 1];
}
